# EDA Lab

# Numpy

- Numpy is the core library for scientific computing in Python. 
- It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [ ]:
import numpy as np

## Arrays

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
- The number of dimensions is the rank of the array.
- The shape of an array is a tuple of integers giving the size of the array along each dimension.

### Create a rank 1 array

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a)


In [ ]:
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

### Create a rank 2 array

In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b)



In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

In [ ]:
#Create a 4 x 4 matrix using lists in numpy array
a = np.array([list(range(1,5)),[2,4,5,6],[3,4,5,6],[5,6,7,8]])

a

#### Numpy array datatypes

In [ ]:
#Numpy array datatypes
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"



In [ ]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"



In [ ]:
x = np.array([1.0, 2.0], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"




#### Numpy functions to create arrays

In [ ]:
# Numpy functions to create arrays

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"



In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"




In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"




In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"



In [ ]:
#random numbers
np.random.seed(12)           #set the seed


In [ ]:
np.random.rand(2, 3)            # 2 x 3 matrix in [0,1]


In [ ]:
np.random.randn(10)             # random normals (mean 0, stdev 1) 


In [ ]:
np.random.randint(0, 2, 10)     # 10 randomly picked 0 or 1

## Array-slicing indexing

- Numpy offers several ways to index into arrays.

- Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.


In [ ]:
# Slice indexing
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)




In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)



In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a)   # Prints "77"

### Boolean array indexing 
- Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a)


In [ ]:
bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.
print(bool_idx)


In [ ]:
# We can use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

In [ ]:
#Alternate way of writing above solution in a single concise statement
print(a[a > 2])

### Mathematical functions operating on arrays

In [ ]:
# Mathematical functions operate elementwise on arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


In [ ]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))


In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))


In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


#### Vector computing
- The dot function computes inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
- dot is available both as a function in the numpy module and as an instance method of array objects

In [ ]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
# Computing sum function of array elements

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


In [ ]:
# Flatten: always returns a flat copy of the orriginal array
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr)
arr_flt = arr.flatten()
print(arr_flt)

In [ ]:
arr_flt.argmin()            #index of minimum element

#### Exercise 1

In [ ]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])
print(x)

In [ ]:
# Compute the mean by row 
## START CODE


## END CODE

In [ ]:
# Compute the mean by column 
## START CODE


## END CODE

In [ ]:
# Compute the mean for all the elements of the array
## START CODE


## END CODE

In [ ]:
# Transposing an array
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

### Reshaping
- The reshape gives a new shape to an array without changing its data. 
- It creates a new array and does not modify the original array itself. 

In [ ]:
# Reshaping an array
x = np.linspace(1, 8, num=8)      # Creates an array of 8 numbers (num=8) in the range (1,8) 
print(x)
print(x.shape)


In [ ]:
# Create a 2D array of shape (4,2) from x
y = x.reshape((4,2))
print(y)
print(y.shape)

In [ ]:
#Stack arrays in sequence vertically (row wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a,b))
print(c)

In [ ]:
#Stack arrays in sequence horizontally (column wise)
c = np.hstack((a,b))
print(c)

### Broadcasting
- provides a means of vectorizing array operations so that looping occurs in C instead of Python. 
- does this without making needless copies of data and usually leads to efficient algorithm implementations.
- More details: https://numpy.org/doc/stable/user/basics.broadcasting.html

<img src=https://numpy.org/doc/stable/_images/broadcasting_2.png></img>

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(x)
print(v)
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

#### Exercise 2 - Functions

In [ ]:
import numpy as np
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    # START CODE
    s = 
    # END CODE
    return s

In [ ]:
x = np.array([1, 2, 3])
sigmoid(x)

#### Exercise 3

Print a reversed NumPy array with the element type float.

*Input Format*

- A single line of input containing space separated numbers.

*Output Format*

- Print the reverse NumPy array with type float.

*Sample Input*

1 2 3 4 -8 -10

*Sample Output*

[-10.  -8.   4.   3.   2.   1.]


In [ ]:
## Start code



## End code

## Reference on Numpy for more details
    - https://numpy.org/doc/stable/reference/
